apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: join-on-reduce
spec:
  vertices:
    - name: http-in
      source:
        http: {}
    - name: kafka-in
      source:
        kafka:
          brokers:
            - my-broker1:19700
            - my-broker2:19700
          topic: my-topic
          consumerGroup: my-consumer-group
    # Both of the incoming Vertices join on this Reduce Vertex
    - name: compute-sum
      udf:
        container:
          # Compute the sum, see https://github.com/numaproj/numaflow-go/tree/main/pkg/function/examples/sum
          image: quay.io/numaio/numaflow-go/reduce-sum
        groupBy:
          window:
            fixed:
              length: 10s
          keyed: false
          storage:
            persistentVolumeClaim:
              volumeSize: 10Gi
              accessMode: ReadWriteOnce
    - name: sink
      scale:
        min: 1
      sink:
        udsink:
          container:
            # A redis sink for e2e testing, see https://github.com/numaproj/numaflow-sinks/tree/main/redis-e2e-test-sink
            image: quay.io/numaio/numaflow-sink/redis-e2e-test-sink:latest
  edges:
    - from: http-in
      to: compute-sum
    - from: kafka-in
      to: compute-sum
    - from: compute-sum
      to: sink
